# Generated by Django 2.2.4 on 2019-08-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xuanzuo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mettingName', models.CharField(max_length=100, verbose_name='会议名称')),
                ('result', models.CharField(max_length=500, verbose_name='结果集')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='metting',
            field=models.ManyToManyField(to='xuanzuo.Metting'),
        ),
    ]
